package com.hyk.univ.common.exception;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;

@Getter
@RequiredArgsConstructor
public enum ErrorCode {

  INVALID_CREDENTIALS(HttpStatus.UNAUTHORIZED, "INVALID_CREDENTIALS"),
  FORBIDDEN(HttpStatus.FORBIDDEN, "FORBIDDEN"),
  NOT_OWN_COURSE(HttpStatus.FORBIDDEN, "NOT_OWN_COURSE"),
  USER_NOT_FOUND(HttpStatus.NOT_FOUND, "USER_NOT_FOUND"),
  COURSE_NOT_FOUND(HttpStatus.NOT_FOUND, "COURSE_NOT_FOUND"),
  ENROLLMENT_NOT_FOUND(HttpStatus.NOT_FOUND, "ENROLLMENT_NOT_FOUND"),
  COURSE_FULL(HttpStatus.CONFLICT, "COURSE_FULL"),
  COURSE_CLOSED(HttpStatus.CONFLICT, "COURSE_CLOSED"),
  CANNOT_CLOSE_COURSE(HttpStatus.UNPROCESSABLE_ENTITY, "CANNOT_CLOSE_COURSE"),
  CREDIT_LIMIT_EXCEEDED(HttpStatus.CONFLICT, "CREDIT_LIMIT_EXCEEDED"),
  DUPLICATE_ENROLLMENT(HttpStatus.CONFLICT, "DUPLICATE_ENROLLMENT"),
  USER_ALREADY_EXISTS(HttpStatus.CONFLICT, "USER_ALREADY_EXISTS"),
  WRONG_ACADEMIC_MODE(HttpStatus.UNPROCESSABLE_ENTITY, "WRONG_ACADEMIC_MODE");

  private final HttpStatus status;
  private final String code;

}
